### PR TITLE
Moving css preprocessing into webpack

### PR DESCRIPTION
**Pull request by geekyme**
Hi, I made some adjustments to allow webpack to handle the css processing instead of using gulp watch + livereload. I think webpack's hot-module reloading is more efficient. 

For example sake, I use stylus for preprocessing (stylus is clean and powerful!) and the plugin nib for browser prefixing. 

I've checked both the production and dev builds of this approach and functionality-wise, everything remains the same. Resources are correctly generated with cache busting too. 

Because I allow webpack to handle css preprocessing, I've also renamed webpack's build folder to /static/ instead of /js/. I've renamed all references in the source files and gulp too.

### CODE REVIEW

**Comment by gpbl** [comment]
Hi @geekyme thank you for the tips, I'll definitely check them out. I'm also not happy with the gulp solution – I'd prefer to keep gulp out as much as possible. 

Some radical changes are coming (I hope soon), because of recent discoveries and best practices... so I'm not merging the PR for now. Anyway thank you again and sorry for the late answer, the notification went lost somewhere...

**Comment by geekyme** [comment]
Sure. Oh cool recent discoveries and best practices?

**Comment by gpbl** [comment]
yep, mainly the app structure, use of reflux, intl support and deep use of the 6to5 transpiler :-)
not a progress on reflux server-rendering, yet: but I'll dive into that soon. when I'm ready I hope to put all the learning in this template.

**Comment by gpbl** [comment]
@geekyme how do you tell webpack where is the entry point for the stylus file? I thought this should be made through a a `require` in the entry js files... but I can't see it in your code.

**Comment by geekyme** [comment]
I have the call in client.jsx :)

**Comment by gpbl** [comment]
I see... thanks!

**Comment by gpbl** [comment]
@geekyme I changed everything :-) Now there's no need to use gulp anymore, I moved all to webpack. Thanks again for the invaluable insights!

**Comment by geekyme** [comment]
You are doing an awesome work with this repo dude. 

Question: is there any reason why you prefer fluxible's router over react-router ?

**Comment by gpbl** [comment]
Yeah react-router didn't play well with my flux implementation :( The fluxible's router fits better.

**Comment by geekyme** [comment]
Really? Wat kind of issues did u face?

**Pull request closed without merging**
