### PR TITLE
ngrok and deploy do DO with azk

### PR DESCRIPTION
**Pull request by saitodisse**
This PR is intended to make it easy to one run the project on his machine.
Using [azk](http://azk.io/), the project is run in a separated context (in containers), so you don't even need Node.js installed on your machine. It can start the application in both development and production modes.

Using containers, we can add other stuff, like databases, elastic search, workers, and be sure that they will work on others' machine.

- https://github.com/azukiapp/azk
- http://images.azk.io

#### README.md (changed)

Minimal description on README and a link that points to [https://github.com/saitodisse/isomorphic500/blob/azkfile-ngrok/Azkfile.md](https://github.com/saitodisse/isomorphic500/blob/azkfile-ngrok/Azkfile.md)

### CODE REVIEW

**Comment by gpbl** [comment]
thanks @saitodisse for the PR – honestly i'm not sure I want to introduce a more complex architecture to launch the app. While I understand the benefits, I'd better keep the project's focus on the app itself. What do you think?

**Comment by saitodisse** [comment]
@gpbl 

thanks for the swift reply! 

although I see your point (it is indeed a more "complex" architecture in the end), I believe you may be missing the fact that azk automates everything so that the net result is a more sophisticated setup for the developer's benefit, without any added perceived complexity for him

think of Heroku, but on your local development machine… and with permissions to see everything "under the hood" and interfere if you want to

and you'll still be able to start the application with a single command (`azk start`)

if you haven't done it yet, I'd like to invite you to test it :) 

your code remains untouched… azk doesn't really "mess" with it… no need to use azk to use your application

finally, using azk remains only as an option

for a more detailed demonstration of how azk would benefit the initial setup of the application and the addition of new features by other programmers, I'd like to recommend our tutorial below: 

https://medium.com/azuki-news/using-azk-along-the-development-cycle-of-a-previously-existing-application-c16579fce5eb

**Comment by gpbl** [comment]
I admit I was aware about azk and ngrok but I never tried to work with them. 😅 ...time to start then! If people are using this project to understand an universal app with flux and react, I fear they feel overwhelmed by the quantity of docs to read to understand its architecture.

Anyway I'd be happy to contribute my little to spread azk. Let me first try it before merging ...!

**Comment by saitodisse** [comment]
@gpbl, I've changed the README:
"Minimal description on README and a link that points to [https://github.com/saitodisse/isomorphic500/blob/azkfile-ngrok/Azkfile.md](https://github.com/saitodisse/isomorphic500/blob/azkfile-ngrok/Azkfile.md)"

There is a deploy to **Digital Ocean** with **azk** option, now.

**Comment by saitodisse** [comment]
I’m closing this PR for while.
Please, feel free to reopen it at any time if you decide to plug a database to store data.
It will also make easier for people who want to deploy their own Isomorphic500 project to DigitalOcean as we demosntrate in this link: https://medium.com/@felipe.arenales/howto-run-project-e-o-deploy-1cf46c80dbd0

Meanwhile I invite you to check __azk__’s `run project` gallery with some unmodified open-source projects forks: https://github.com/run-project/gallery
We'd really like to add Isomorphic500 project to the list. 
Best regards,

**Pull request closed without merging**
