### PR TITLE
Added nodemon

### PR DESCRIPTION
**Pull request by robink**
Allow server to reload on pure 'server-side' files change.

### CODE REVIEW

**Comment by gpbl** [comment]
Ehy thanks for this, trying it before merging...

**Comment by gpbl** [comment]
@robink working great, thanks! Could you move `nodemon` to dev dependencies ? Or is there a reason for keeping it into the prod deps?

**Comment by robink** [comment]
updated !

**Comment by gpbl** [comment]
Thanks!

**Pull request merged**
